name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
        local-cache: true
    - name: configure
      run: cd jni && ndk-build V=1
